### ISSUE TITLE
[experimental-multires] Issues with 1080i

### ISSUE THREAD

**Issue by plaes** [AlphamaxMedia/netv2-fpga#11] opened 2019-06-05 17:33 UTC
When testing multiarch branch 1080i (commit e3514be72f) I ran into following issues:

1) One pixel shift of lines
![image](https://user-images.githubusercontent.com/91895/58973690-3cd0bd80-87c9-11e9-80ce-504e0c1ea592.png)

2) Garbled overlay colors (seems to always happen with one certain TV channel)
![image](https://user-images.githubusercontent.com/91895/58975834-9daec480-87ce-11e9-98eb-c3248e8f2184.png)

3) Whole overlay shifted left after rebooting FPGA (~3 times out of 10 reboots). Sometimes reinitializing with `1080i` command helps.

![image](https://user-images.githubusercontent.com/91895/58976874-29295500-87d1-11e9-87ef-7ed954c7aa23.png)

**Comment by bunnie** [comment] 2019-06-06 09:59
Thanks for reporting these. this is actually three separate issues. Since they are all grouped together I will just cherry pick the most convenient one to work on and branch it to a new issue when I get the time.

**Comment by bunnie** [comment] 2019-09-22 06:32
I think the most recent patch pushed should address the 1st and 3rd issues. The 1st issue for sure is fixed. The 3rd issue you might still see about an 8-pixel shift from boot to boot, but I haven't been able to reliably reproduce the problem. I think it's related to the fifo sync between the overlay and oncoming stream, and it seems rare enough I'll close this for now and we can open again in a separate bug if it's really an issue.

The color being off on a particular channel -- I haven't been able to reproduce that problem, but also, if the problem is due to color space being changed on a given channel by the broadcaster, there's nothing I can actually do about that because the colorspace info is encrypted and it would be a 1201 DMCA violation to read that out and adjust the overlay to match. So that bug may have to wait for the courts to decide this is a thing we should be able to do with our video.

**Closed as completed by bunnie** 2019-09-22 06:32 UTC
